# Generated by Django 4.2.3 on 2023-07-26 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="developmentagent",
            table="development_agent",
        ),
    ]
