# Generated by Django 4.2.3 on 2023-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registries", "0004_alter_kebele_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kebele",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
