# Generated by Django 4.2.3 on 2023-07-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registries", "0005_alter_kebele_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="woreda",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="woreda",
            unique_together={("name", "zone")},
        ),
    ]
