# Generated by Django 4.2.3 on 2023-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registries", "0007_alter_zone_name_alter_zone_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentagent",
            name="telegram_phone_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="developmentagent",
            name="alternate_phone_number",
            field=models.TextField(blank=True, null=True),
        ),
    ]
